PelatihanLanjutan/Controllers/AkunController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PelatihanLanjutan.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace PelatihanLanjutan.Controllers
{
    public class AkunController : Controller
    {
        private readonly AppDbContext _context;

        public AkunController(AppDbContext context)
        {
            _context = context;
        }
        public IActionResult Daftar()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Daftar(User datanya)
        {
            var deklarrole = _context.Tb_Roles.Where(x => x.Id == "1").FirstOrDefault();

            datanya.Roles = deklarrole;

            _context.Add(datanya); //insert to tb user
            _context.SaveChanges(); //eksekusi

            return RedirectToAction("Masuk");
            // return RedirectToAction(ControllerName:Akun ActionName:Masuk);
            //return redirect("Masuk")
        }

        public IActionResult Masuk()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Masuk(User datanya)
        {
            var cari = _context.Tb_User.Where( //proses pencarian data
                                            bebas =>
                                            bebas.Username == datanya.Username
                                            &&
                                            bebas.Password == datanya.Password
                                            ).FirstOrDefault(); //hanya dapat 1 data

            var cariusername = _context.Tb_User.Where( //proses pencarian data
                                            bebas =>
                                            bebas.Username == datanya.Username
                                            ).FirstOrDefault();
            if (cariusername != null)
            {
                var cekpassword = _context.Tb_User.Where( //proses pengecekan username
                                            bebas =>
                                            bebas.Username == datanya.Username
                                            &&
                                            bebas.Password == datanya.Password
                                            )
                    .Include(bebas2 => bebas2.Roles)
                    .FirstOrDefault();

                if (cekpassword != null)
                {
                    //proses tampungan data
                    var daftar = new List<Claim>
                    {
                        new Claim("Username", cariusername.Username),
                        new Claim("Roles", cariusername.Roles.Id),
                    };

                    //proses daftar Auth
                    await HttpContext.SignInAsync(
                        new ClaimsPrincipal(
                            new ClaimsIdentity(daftar, "Cookies", "Username", "Role")
                        )
                    );

                    if (cariusername.Roles.Id == "1")
                    {
                        //return RedirectToAction(controllerName: "Blog", actionName: "Index");
                        return Redirect("/Admin/Home");
                    }
                    else if (cariusername.Roles.Id == "2")
                    {
                        return Redirect("/User/Home");
                    }

                    return RedirectToAction(controllerName: "Home", actionName: "Privacy");
                }
                ViewBag.pesan = "Password salah";
                return View(datanya);
            }
            ViewBag.pesan = "Username tidak terdaftar";
            return View(datanya); 
        }
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync();
            return Redirect("/");
        }
    }
}

PelatihanLanjutan/Controllers/BlogController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PelatihanLanjutan.Helper;
using PelatihanLanjutan.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PelatihanLanjutan.Controllers
{
    [Authorize]
    public class BlogController : Controller
    {
        private readonly AppDbContext _context;

        public BlogController(AppDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            var banyakdata = new BlogDashBoard();
            banyakdata.blog = _context.Tb_Blog.Include(x => x.User).ToList();
            banyakdata.user = _context.Tb_User.Include(x => x.Roles).ToList();
            return View(banyakdata);
        }
        public IActionResult Create() //menampilkan kolom inputan(view)
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Blog parameter) //menerima inputannya
        {
            if (ModelState.IsValid)
            {
                //proses masukan ke database
                //parameter.Id = BuatPrimary.buatPrimary() //ini dari helper(error karna pake integer)
                string nama = User.GetUsername();
                    parameter.User = _context.Tb_User.FirstOrDefault(x => x.Username == nama);
             

                _context.Add(parameter);
                await _context.SaveChangesAsync();

                return Redirect("Index");
            }
            return View(parameter);
        }

        public async Task<IActionResult> Delete(int id)
        {
            var cari = _context.Tb_Blog.Where(x => x.Id == id).FirstOrDefault();
            if (cari == null)
            {
                return NotFound();
            }

            _context.Tb_Blog.Remove(cari);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Detail(int id)
        {
            var data = await _context.Tb_Blog.FirstOrDefaultAsync(a => a.Id == id);
            if(data == null)
            {
                return NotFound();
            }
            return View(data);
        }

        public async Task<IActionResult> Edit(int id)
        {
            var cari = await _context.Tb_Blog.FirstOrDefaultAsync(x => x.Id == id);
            if (cari== null)
            {
                return NotFound();
            }
            return View(cari);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Blog data)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Tb_Blog.Update(data);
                    await _context.SaveChangesAsync();
                }
                catch
                {
                    return NotFound();
                }
                return RedirectToAction("Index");
            }
            return View(data);
        }
    }
}

PelatihanLanjutan/Views/Shared/_Layout.cshtml
@using PelatihanLanjutan.Helper

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PelatihanLanjutan</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Go-Blogs</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Blog" asp-action="Index">Tampil Data</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Blog" asp-action="Create">Blog</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Akun" asp-action="Daftar">Sign In</a>
                        </li>
                    </ul>
                </div>
                <div>
                    @{
                        string cek = User.GetUsername();
                        if (cek != null)
                        {
                            @User.GetUsername()
                            <a asp-action="Logout" asp-controller="Akun" style="color:red" class="bi bi-box-arrow-right"
                               onclick="if (!confirm('Yakin Untuk Keluar?')) { return false; }">Keluar</a>
                        }
                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - PelatihanLanjutan - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

PelatihanLanjutan/Views/Shared/_LayoutAkun.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>AdminLTE 3 | Registration Page</title>

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/plugins/fontawesome-free/css/all.min.css">
    <!-- icheck bootstrap -->
    <link rel="stylesheet" href="~/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/dist/css/adminlte.min.css">
</head>
<body class="hold-transition register-page">
    <div class="register-box">
        <div class="register-logo">
            <a asp-controller="Home" asp-action="Index">Go-Blogs</a>
        </div>

        <div class="card">
            <div class="card-body register-card-body">
                <p class="login-box-msg">Register a new membership</p>

                @RenderBody()

            </div>
            <!-- /.form-box -->
        </div><!-- /.card -->
    </div>
    <!-- /.register-box -->
    <!-- jQuery -->
    <script src="~/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="~/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/dist/js/adminlte.min.js"></script>
</body>
</html>